declare module "material-ui-legacy/styles/MuiThemeProvider"
declare module "material-ui-legacy/SelectField"
declare module "material-ui-legacy/MenuItem"
declare module "material-ui-legacy/styles/getMuiTheme"
declare module "material-ui-legacy/styles/colors"
declare module "material-ui-legacy/utils/colorManipulator"
declare module "material-ui-legacy"
